language: python
addons:
  apt:
    packages:
    - zlib1g-dev
    - libblas-dev
    - liblapack-dev
    - libgfortran3
    - libncurses5-dev
python:
  - "3.4"
sudo: false
install:
  - "source ./install_dependencies.sh"
script:
  - "python setup.py test"